name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amazonlinux:2023

    
    steps:
      - uses: actions/checkout@v4

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Build
        run: make

      - name: Verify executable
        run: test -f ProxyServer
