name: Build

on: 
  pull_request:
  push:
    branches:
      - test
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Compiler
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Build
        run: make

      - name: Verify executable
        run: test -f ProxyServer
