name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amazonlinux:2023

    steps:
      - uses: actions/checkout@v4

      - name: Install compiler
        run: |
          dnf install -y gcc-c++ make tar

      - name: Build
        run: make

      - name: Verify executable
        run: test -f ProxyServer

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ProxyServer
          path: ProxyServer

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ProxyEnv

    steps:
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: ProxyServer

      - name: Make executable
        run: chmod +x ProxyServer

      - name: Copy executable
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_EC2_PRIV_KEY }}
          source: "ProxyServer"
          target: "/home/ec2-user/"

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_EC2_PRIV_KEY }}
          script: |
            sudo systemctl restart proxy.service
