name: Deploy

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Compiler
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Build
        run: make

      - name: Verify executable
        run: test -f ProxyServer
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - run: make

    - name: Copy executable
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_EC2_PRIV_KEY }}
        source: "ProxyServer"
        target: "/home/ec2-user/"
        
    - name: Restart service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_EC2_PRIV_KEY }}
        script: |
          sudo systemctl restart proxy.service
